### ISSUE TITLE
Setting up the development environment

### ISSUE THREAD

**Issue by mkaring** [nirin/msbuild-sdks#7]
Hello,

I tried setting up my local development environment to handle this repository. How ever it fails when trying to load the projects, because it can't resolve the SDKs.
Is there anything special that needs to be done to get this working?

Also your command line tools fail to resolve the `vsdev` command.

I need some hints on how to get this working and how to setup my environment to do more extensive tests and send some contributions your way.

**Comment by Nirmal4G** [comment]
#### My Way:

That's because I'm using custom scripts and SDKs to build them. I don't know if it'll work for you. But here are the scripts:

[vsbuild.cmd](https://github.com/nirin/msbuild-sdks/files/2085601/vsbuild.cmd.txt)
[vsdev.cmd](https://github.com/nirin/msbuild-sdks/files/2085602/vsdev.cmd.txt)

Put them in your `PATH` and set env var `MSBuildSDKsPathNew` point to the custom SDKs directory you've created somewhere (e.g.: `D:\Projects\Packages\Sdks`).
- Add a symbolic links to all the SDKs within `Source` folder of this repo to that custom SDKs dir
- And possibly create symbolic links to all SDKs that you're using, from the latest `dotnet-sdk` install!

**Comment by Nirmal4G** [comment]
#### `global.json` way:

- Create a `global.json` listing the SDKs and it's latest version from the myget gallery.
- Use a `NuGet.config` to point to the myget gallery url and a local `Packages` dir (e.g.: `D:\Projects\Packages\Local`) and publish in that dir to test yours and my builds.

**Comment by mkaring** [comment]
For local testing I found it very helpful to alter the test projects a bit.

Currently they look like this:
```XML
<Project Sdk="MSBuild.NET.Extras.Sdk">

…

</Project>
```

The following alteration causes them to still work, with the added advantage that they directly reference the current development state of the package:
```XML
<Project>
	<Import Project="$(MSBuildThisFileDirectory)..\..\..\Source\MSBuild.NET.Extras.Sdk\Sdk\Sdk.props" />

…

	<Import Project="$(MSBuildThisFileDirectory)..\..\..\Source\MSBuild.NET.Extras.Sdk\Sdk\Sdk.targets" />
</Project>
```

Note that the `$(RepoRootDir)` property cannot be used, because Visual Studio does not resolve the `Directory.Build.*` files while loading the project.

If you like that change, I'll send you a PR within a could of minutes. This change also uncovered some additional problems.

**Comment by Nirmal4G** [comment]
We need to test them as SDK Reference, so this is not an ideal solution for dev/test cycle.
I was not expecting anyone to contributing back to this, as these are used internally for our projects.
I already have a solution that I've been working on. I'll commit them soon as soon as I complete my pending work.

**Comment by Nirmal4G** [comment]
> This change also uncovered some additional problems.

If you can, please test with the latest develop commit, any issues stand out?
